/*
  main.c for Nucleo-F446RE (CubeIDE)

  This main.c assumes you used CubeMX to generate the project (MX_GPIO_Init,
  MX_USART2_UART_Init, SystemClock_Config, and the HAL init code are generated).
  Place this file in your project's Src/ replacing the generated main.c (or
  merge the relevant parts into the generated main.c).

  This file calls a C++ inference function `run_inference_demo()` which must be
  implemented in a separate C++ source (example provided as tflm_inference.cpp).
  The C++ file requires TensorFlow Lite Micro sources and kws_model.c/h produced
  by convert_tflite_to_c.py.

  Notes:
  - Ensure kws_model.h/.c and (optional) kws_input_sample.h are added to the
    project Inc/ and Src/ respectively.
  - Make sure the project is configured to compile C++ sources (CubeIDE supports this).
  - Add the TFLM include paths to the project (tensorflow/lite/micro/...).
*/

#include "main.h"       // CubeMX-generated header (includes HAL drivers and prototypes)
#include <string.h>
#include <stdio.h>

/* Declare the inference function implemented in C++ (tflm_inference.cpp).
   Use C linkage so main.c can call it. */
#ifdef __cplusplus
extern "C" {
#endif
void run_inference_demo(void);
#ifdef __cplusplus
}
#endif

/* Redirect printf to UART (optional). If you want to use printf for debug,
   implement _write or fputc redirection depending on your toolchain.
   Example below uses HAL_UART_Transmit via huart2 (CubeMX typically creates huart2). */
#ifdef __GNUC__
/* With GCC, small printf (with float support disabled) calls _write */
int _write(int file, char *ptr, int len)
{
    /* Replace huart2 with the UART handle generated in your project (e.g., huart2) */
    extern UART_HandleTypeDef huart2;
    HAL_UART_Transmit(&huart2, (uint8_t*)ptr, len, HAL_MAX_DELAY);
    return len;
}
#endif

int main(void)
{
  /* MCU Configuration--------------------------------------------------------*/
  /* Reset of all peripherals, Initializes the Flash interface and the Systick. */
  HAL_Init();

  /* Configure the system clock (CubeMX generates this function). */
  SystemClock_Config();

  /* Initialize all configured peripherals (generated by CubeMX) */
  MX_GPIO_Init();
  MX_USART2_UART_Init();

  /* Optional: brief message on UART to indicate startup */
  const char *msg = "Nucleo-F446RE starting... Running inference demo shortly.\r\n";
  HAL_UART_Transmit(&huart2, (uint8_t*)msg, strlen(msg), HAL_MAX_DELAY);

  /* Small delay to let terminal open */
  HAL_Delay(200);

  /* Run the TFLM inference demo (C++ function). The function performs:
     - model loading (from kws_model array)
     - AllocateTensors()
     - fill input tensor (from kws_input_sample or zeros)
     - Invoke()
     - Print predicted class via UART
     Note: function handles errors and prints via UART reserved huart2. */
  run_inference_demo();

  /* Main loop: you can call inference periodically, or leave as-is.
     For demo purposes we toggle the user LED every 2 seconds. */
  while (1)
  {
    HAL_GPIO_TogglePin(LD2_GPIO_Port, LD2_Pin);
    HAL_Delay(2000);
  }
}
